AWSTemplateFormatVersion: '2010-09-09'
Description: Python-Levenshtein
Globals:
  Function:
    Runtime: python3.7
    Timeout: 3
Resources:
  PythonLevenshteinLambdaLayer:
    Properties:
      CompatibleRuntimes:
      - python3.7
      ContentUri: s3://lambda-layer-geetharam/layer.zip
      Description: Python Levenshtein Lambda Layer
      LayerName: python-Levenshtein
      LicenseInfo: MIT
      RetentionPolicy: Retain
    Type: AWS::Serverless::LayerVersion
Transform: AWS::Serverless-2016-10-31
